### PR TITLE
Update sk translation

### PR DESCRIPTION
**Pull request by atomsymbol**
This pull request contains Slovak translation updates from https://localazy.com/p/openchia/phrases/1186 which cannot be downloaded because of Localazy's free plan limitations and pricing.

@william-gr Please merge. Thanks.

See also: https://github.com/openchia/web/issues/64

### CODE REVIEW

**Review by william-gr — APPROVED** [review]
Thanks

**Comment by william-gr** [comment]
The build failed, i will look at what happened later, i reverted it meanwhile

**Comment by atomsymbol** [comment]
The merged XML file has `xml:space="preserve"` attributes removed. Is that OK?

**Comment by atomsymbol** [comment]
````
# cat angular-errors.log 
[error] Error: Localization currently only supports using one type of translation file format for the entire application.
    at Object.configureI18nBuild (/tmp/build/node_modules/@angular-devkit/build-angular/src/utils/i18n-options.js:192:23)
    at async Object.generateI18nBrowserWebpackConfigFromContext (/tmp/build/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:65:36)
    at async initialize (/tmp/build/node_modules/@angular-devkit/build-angular/src/browser/index.js:64:62)
    at async SwitchMapSubscriber.project (/tmp/build/node_modules/@angular-devkit/build-angular/src/browser/index.js:114:17)
````

**Pull request merged**
